name: AWS Deploy Action

on:
  push:
    branches:
      - main
      - chore/aws

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Install OpenTofu
        run: |
          curl --proto '=https' --tlsv1.2 -fsSL https://get.opentofu.org/install-opentofu.sh -o install-opentofu.sh
          chmod +x install-opentofu.sh
          ./install-opentofu.sh --install-method deb
          rm install-opentofu.sh

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Run OpenTofu plan
        id: tofu-apply
        working-directory: tofu
        run: |
          tofu apply
          echo "site-bucket=$(tofu output site_bucket)" >> ${GITHUB_OUTPUT}

      - name: Upload to S3
        run: aws s3 sync --delete ./dist s3://${{ steps.tofu-apply.outputs.site-bucket }}

